// Maps the Indicators-tab display name (lib/data.js INDICATORS[].name) to its
// Supabase series slug in v_indicator_analytics. Keeping this here keeps the
// comparison tool in sync with the tab without duplicating the catalog.
//
// "Renter-Age Employment (20-34)" is intentionally absent: it's a composite of
// two BLS cohort slugs (emp_2024 + emp_2534), not a single fetchable series, so
// it isn't offered as a comparison line.

export const SLUG_BY_NAME = {
  "Apartment Investment Index (AIMI)": "aimi",
  "AIMI Rent Component": "aimi_rent_index",
  "AIMI Value Component": "aimi_value_index",
  "Existing Home Sales": "existing_home_sales",
  "Rent Burden": "acs_rent_burden",
  "Median Gross Rent": "acs_median_gross_rent",
  "Median Household Income": "acs_median_hh_income",
  "Median Home Value": "acs_median_home_value",
  "2-Year Treasury": "treasury_2y",
  "Corporate Credit Spread (BAA)": "baa_spread",
  "High-Yield Credit Spread": "hy_oas",
  "SOFR (Overnight Rate)": "sofr",
  "MF Lending Standards (SLOOS)": "mf_lending_standards",
  "Job Openings (JOLTS)": "jolts_openings",
  "Quits Rate (JOLTS)": "jolts_quits",
  "Multifamily Building Permits": "permits_5plus",
  "Home Value Index": "zhvi_national",
  "Absorption Rate (3-Mo)": "absorption",
  "Renter Demand Index (ZORDI)": "zordi",
  "Unemployment Rate": "unemployment",
  "Days On Market": "days_on_market",
  "National Vacancy Rate": "rental_vacancy",
  "Market Rent Growth (All Rentals)": "zori_national",
  "Renter Delinquency Rate": "renter_delinquency",
  "Cap Rate (National Avg)": "cap_rate",
  "Wage Growth": "wage_growth",
  "Real Wage Growth": "wage_growth_real",
  "Job Growth": "employment",
  "Gross Domestic Product": "gdp",
  "Real Consumer Spending": "real_pce",
  "Consumer Sentiment (UMich)": "consumer_sentiment",
  "Inflation": "cpi_headline",
  "Interest Rates": "fed_funds",
  "National Foreclosure Rate": "foreclosure",
  "CRE Loan Delinquency Rate": "cre_delinquency",
  "Credit Card Delinquency Rate": "cc_delinquency",
  "Consumer Loan Delinquency Rate": "consumer_loan_delinquency",
  "Mortgage Delinquency Rate (Single-Family)": "mortgage_delinquency",
  "Household Debt Service Ratio": "debt_service_ratio",
  "Consumer Credit Outstanding (Total)": "consumer_credit_total",
  "Revolving Consumer Credit": "consumer_credit_revolving",
  "Nonrevolving Consumer Credit": "consumer_credit_nonrevolving",
  "Yield Curve Spread": "yield_spread",
  "Initial Jobless Claims": "initial_claims",
  "Leading Indicator (OECD)": "cli_oecd",
};
